// @ts-nocheck
export const DEFAULT_LAYOUT = {
  lg: [
    {
      h: 2.5,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 0,
    },
    {
      h: 2.5,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 6,
      x: 6,
      y: 0,
    },
    { h: 3, i: 'MY_DESIGNS', moved: false, static: false, w: 6, x: 0, y: 2.5 },
    { h: 3, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 6, y: 2.5 },
    {
      h: 4,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 5.5,
    },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 12, x: 0, y: 9.5 },
  ],
  md: [
    {
      h: 2.5,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 5,
      x: 0,
      y: 0,
    },
    {
      h: 2.5,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 5,
      x: 5,
      y: 0,
    },
    { h: 3, i: 'MY_DESIGNS', moved: false, static: false, w: 5, x: 0, y: 2.5 },
    { h: 3, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 5, x: 5, y: 2.5 },
    {
      h: 4,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 10,
      x: 0,
      y: 5.5,
    },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 10, x: 0, y: 9.5 },
  ],
  sm: [
    {
      h: 2.5,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 0,
    },
    {
      h: 2.5,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 2.5,
    },
    { h: 3, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 0, y: 5 },
    { h: 3, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 3, x: 3, y: 5 },
    {
      h: 4,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 6,
      x: 0,
      y: 8,
    },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 12 },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 2 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 4 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 6 },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 0,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 2 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 4 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 6 },
  ],
};

export const LOCAL_PROVIDER_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 0,
    },
  ],
};

export const OVERVIEW_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
};
