name: Build Server

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      backend-artifact:
        description: 'Name of the backend artifact'
        value: 'meshery-backend' 

    secrets: {}

jobs:
  build-backend:
    name: Backend build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: meshery/meshery

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "1.25"
          cache: true

      - name: Build backend
        run: |
          GOPROXY=https://proxy.golang.org,direct GOSUMDB=off GO111MODULE=on \
          go build -tags draft ./server/cmd/main.go ./server/cmd/error.go

      - name: Upload backend artifact
        id: upload
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: meshery-backend
          path: ./main